apache/maven-archetype

archetype-common/pom.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/archetype/pom.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/archetype/src/main/resources/META-INF/archetype-post-generate.groovy, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/archetype/src/main/resources/archetype-resources/pom.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/invoker.properties, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/pom.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/project.properties, maven-archetype-plugin/src/it/projects/ARCHETYPE-536_groovy-grape/verify.groovy
see https://issues.apache.org/jira/browse/ARCHETYPE-536
=> ARCHETYPE-536 Update Groovy Dependency and Include Ivy Dependency

Jenkinsfile, archetype-common/pom.xml, archetype-common/src/main/java/org/apache/maven/archetype/common/DefaultPomManager.java, archetype-common/src/main/java/org/apache/maven/archetype/common/PomManager.java, archetype-common/src/main/java/org/apache/maven/archetype/common/util/PomUtils.java, archetype-common/src/main/java/org/apache/maven/archetype/generator/DefaultArchetypeGenerator.java, archetype-common/src/main/java/org/apache/maven/archetype/generator/DefaultFilesetArchetypeGenerator.java, archetype-common/src/main/java/org/apache/maven/archetype/generator/FilesetArchetypeGenerator.java, archetype-common/src/main/java/org/apache/maven/archetype/old/DefaultOldArchetype.java, archetype-common/src/main/java/org/apache/maven/archetype/old/OldArchetype.java, archetype-common/src/test/java/org/apache/maven/archetype/old/ArchetypeTest.java, pom.xml
dom4j removal - use Java XML API - removed duplicated method with dom4j (calling it twice)
=> dom4j removal - use Java XML API - reused the same method twice

maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/CreateArchetypeFromProjectMojo.java, pom.xml
Signed-off-by: Mat Booth <mat.booth@redhat.com>
=> [ARCHETYPE-569] Update to latest version of plexus utils

archetype-common/src/main/java/org/apache/maven/archetype/common/Constants.java, archetype-common/src/main/java/org/apache/maven/archetype/source/LocalCatalogArchetypeDataSource.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/UpdateLocalCatalogMojo.java
Implements [ARCHETYPE-583](https://issues.apache.org/jira/browse/ARCHETYPE-583)
=> [ARCHETYPE-583] Allow skip non-archetypes

pom.xml
=> [MARCHETYPE-592] update commons-io

pom.xml
=> {MARCHETYPE-593] update artifact transfer

.gitignore
=> add some metafiles to .gitignore

maven-archetype-plugin/pom.xml, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfigurator2Test.java, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfiguratorTest.java, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationQueryerTest.java, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeSelectionQueryerTest.java, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeSelectorTest.java
@michael-o This is the latest version that works with Java 7. The EasyMock API changed since the tests were written so there's a lot of test rewrites here.
=> [ARCHETYPE-594] Update EasyMock

pom.xml
these classes are from JDOM, not dom4j
=> docs: correct comment, JDOM != dom4j

archetype-common/src/main/java/org/apache/maven/archetype/source/RemoteCatalogArchetypeDataSource.java
Fixes https://issues.apache.org/jira/browse/ARCHETYPE-585
=> [ARCHETYPE-585] Fix NullPointerException

archetype-common/src/main/java/org/apache/maven/archetype/creator/FilesetArchetypeCreator.java, maven-archetype-plugin/src/it/projects/ARCHETYPE-531_ear-modules/invoker.properties, maven-archetype-plugin/src/it/projects/ARCHETYPE-531_ear-modules/pom.xml
Treat no `<modules />` element as no modules at all
=> [ARCHETYPE-531] Treat no modules element as no modules at all

.github/workflows/maven.yml, archetype-common/src/main/java/org/apache/maven/archetype/common/util/Format.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/IntegrationTestMojo.java, pom.xml
- add ci build github action
- do not fail in javadoc warnings
- fix javadoc error
- fix javadoc
- fix javadoc
=> Add github actions

archetype-common/src/main/java/org/apache/maven/archetype/ArchetypeGenerationRequest.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/CreateProjectFromArchetypeMojo.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfigurator.java
=> [ARCHTYPE-308] optionally ask for properties with default values in

archetype-common/src/main/java/org/apache/maven/archetype/DefaultArchetypeManager.java
I had some issues getting the catalog so I added a debug message when the catalog cannot be downloaded
=> adding a debug message for getRemoteCatalog

pom.xml
First of several steps needed to bring this up to parent pom 39
=> [ARCHETYPE-642] update plexus-utils to 3.5.1

maven-archetype-plugin/src/it/projects/ARCHETYPE-622_main_build_settings/verify.groovy, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/IntegrationTestMojo.java
https://issues.apache.org/jira/browse/ARCHETYPE-657
=> [ARCHETYPE-657] store IT data in target/ instead of target/classes/

archetype-common/pom.xml, archetype-common/src/main/java/org/apache/maven/archetype/VelocityConfigurator.java, archetype-common/src/main/java/org/apache/maven/archetype/generator/DefaultFilesetArchetypeGenerator.java, archetype-common/src/test/java/org/apache/maven/archetype/old/ArchetypeTest.java, maven-archetype-plugin/pom.xml, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfigurator.java, pom.xml
https://issues.apache.org/jira/browse/ARCHETYPE-667
=> [ARCHETYPE-667] Upgrade Velocity from 1.7 to 2.3

archetype-common/pom.xml, archetype-common/src/main/java/org/apache/maven/archetype/ArchetypeGenerationRequest.java, archetype-common/src/main/java/org/apache/maven/archetype/common/ArchetypeArtifactManager.java, archetype-common/src/main/java/org/apache/maven/archetype/common/DefaultArchetypeArtifactManager.java, archetype-common/src/main/java/org/apache/maven/archetype/downloader/DefaultDownloader.java, archetype-common/src/main/java/org/apache/maven/archetype/downloader/Downloader.java, archetype-common/src/main/java/org/apache/maven/archetype/generator/DefaultArchetypeGenerator.java, archetype-common/src/main/java/org/apache/maven/archetype/old/DefaultOldArchetype.java, archetype-common/src/main/java/org/apache/maven/archetype/old/OldArchetype.java, archetype-common/src/main/java/org/apache/maven/archetype/source/LocalCatalogArchetypeDataSource.java, archetype-common/src/test/java/org/apache/maven/archetype/generator/DefaultArchetypeGeneratorTest.java, archetype-common/src/test/java/org/apache/maven/archetype/old/ArchetypeTest.java, archetype-common/src/test/java/org/apache/maven/archetype/test/ArchetypeGenerationTest.java, archetype-common/src/test/java/org/apache/maven/archetype/test/InternalCatalogArchetypesVerificationTest.java, maven-archetype-plugin/pom.xml, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/CreateProjectFromArchetypeMojo.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/IntegrationTestMojo.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfigurator.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeSelector.java, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfigurator2Test.java, maven-archetype-plugin/src/test/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfiguratorTest.java, pom.xml
https://issues.apache.org/jira/browse/ARCHETYPE-673
=> [ARCHETYPE-673] Get rid of maven-artifact-transfer

maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/IntegrationTestMojo.java
https://issues.apache.org/jira/browse/ARCHETYPE-632
This PR is just for logging so no unit test.
=> [ARCHETYPE-632] Add logging conflict line in integration-test

archetype-common/pom.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-565_groovy-json/archetype/src/main/resources/META-INF/archetype-post-generate.groovy, pom.xml
https://issues.apache.org/jira/browse/ARCHETYPE-683
=> [ARCHETYPE-683] Add groovy-json to classpath

maven-archetype-plugin/src/it/projects/ARCHETYPE-606_include-gitignore/test-settings.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-606_include-gitignore/verify.groovy, maven-archetype-plugin/src/it/projects/ARCHETYPE-622_main_build_settings/pom.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-622_main_build_settings/test-settings.xml, maven-archetype-plugin/src/it/projects/ARCHETYPE-622_main_build_settings/verify.groovy, maven-archetype-plugin/src/it/projects/build-and-run-its/test-settings.xml, maven-archetype-plugin/src/it/projects/build-archetype/test-settings.xml, maven-archetype-plugin/src/it/projects/build-ignore-eol/test-settings.xml, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/FileLogger.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/IntegrationTestMojo.java
https://issues.apache.org/jira/browse/ARCHETYPE-681
=> [ARCHETYPE-681] Fix output from archetype verification

archetype-models/archetype-descriptor/src/main/mdo/archetype-descriptor.mdo, maven-archetype-plugin/src/it/projects/ARCHETYPE-606_include-gitignore/src/main/resources/META-INF/maven/archetype-metadata.xml
https://issues.apache.org/jira/browse/ARCHETYPE-684
=> [ARCHETYPE-684] Add default value for fileSet.directory in archetype-descriptor

maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/IntegrationTestMojo.java
https://issues.apache.org/jira/browse/ARCHETYPE-680
=> [ARCHETYPE-680] Use ERROR loglevel in integration test

archetype-common/src/main/java/org/apache/maven/archetype/ArchetypeGenerationRequest.java, archetype-common/src/main/java/org/apache/maven/archetype/generator/DefaultArchetypeGenerator.java, archetype-common/src/main/java/org/apache/maven/archetype/old/DefaultOldArchetype.java, archetype-common/src/test/java/org/apache/maven/archetype/old/ArchetypeTest.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/mojos/CreateProjectFromArchetypeMojo.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeGenerationConfigurator.java, maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeSelector.java
https://issues.apache.org/jira/browse/ARCHETYPE-689
=> [ARCHETYPE-689] Restore removed public methods in ArchetypeGenerationRequest

maven-archetype-plugin/pom.xml
for the change (usually before you start working on it).  Trivial changes like typos do not
require a JIRA issue. Your pull request should address just this issue, without
pulling in other changes.
where you replace `ARCHETYPE-XXX` and `SUMMARY` with the appropriate JIRA issue.
Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
the [Apache License Version 2.0, January …
=> [ARCHETYPE-690] Install archetype-packaging for ITs

archetype-common/src/main/java/org/apache/maven/archetype/common/util/ListScanner.java, archetype-common/src/test/java/org/apache/maven/archetype/common/TestDefaultArchetypeFilesResolver.java, archetype-common/src/test/java/org/apache/maven/archetype/common/util/TestXMLOutputter.java, archetype-common/src/test/java/org/apache/maven/archetype/generator/DefaultArchetypeGeneratorTest.java, archetype-common/src/test/java/org/apache/maven/archetype/repositorycrawler/DefaultRepositoryCrawlerTest.java, archetype-common/src/test/java/org/apache/maven/archetype/test/ArchetypeGenerationTest.java
Debuggers are a thing. This makes builds a little less noisy.
=> Remove a lot of old println detritus

.github/release-drafter.yml
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Add release-drafter configuration

archetype-common/pom.xml, archetype-models/archetype-catalog/pom.xml, archetype-models/archetype-descriptor/pom.xml, archetype-models/pom.xml, archetype-packaging/pom.xml, maven-archetype-plugin/pom.xml, pom.xml
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Bump project version to 3.4.0-SNAPSHOT

.github/pull_request_template.md
Use the same command as in README
=> Remove clean from the PR template

archetype-models/archetype-descriptor/pom.xml, archetype-models/archetype-descriptor/src/main/mdo/archetype-descriptor.mdo
As we add new filed includeCondition
in 5ed7d901ef4a18613023907874ee86cd935a1db9
=> Bump archetype descriptor version to 1.2.0

.github/workflows/maven-verify.yml, archetype-common/src/main/java/org/apache/maven/archetype/common/MavenJDOMWriter.java
https://issues.apache.org/jira/browse/ARCHETYPE-674
It is only a workaround ... whole class `MavenJDOMWriter` should be rewritten or replaced.
=> [ARCHETYPE-674] Workaround for Maven 4

pom.xml
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Bump m-invoker-p to 3.9.1 - to allow build by JDK 25

src/site/apt/index.apt
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Remove not existing module archetype-testing from documentation
